export const flowers = {
  "Arreglos de ocasión": {
    '14 de Febrero': [
      'arreglo floral amor 1.jpg',
      'arreglo floral amor 2.jpg',
      'arreglo floral amor 3.jpg',
      'arreglo floral amor 4.jpg',
      'arreglo floral amor 5.jpg',
      'arreglo floral amor 6.jpg',
      'arreglo floral amor 7.jpg',
      'arreglo floral amor 8.jpg',
      'arreglo floral amor 9.jpg',
      'arreglo floral amor 10.jpg',
      'arreglo floral amor 11.jpg',
      'arreglo floral amor 12.jpg',
      'arreglo floral amor 13.jpg',
      'arreglo floral amor 14.jpg',
      'arreglo floral amor 15.jpg',
      'arreglo floral amor 16.jpg',
      'arreglo floral amor 17.jpg',
      'arreglo floral amor 18.jpg',
      'arreglo floral amor 19.jpg',
      'arreglo floral amor 20.jpg',
      'arreglo floral amor 21.jpg',
      'arreglo floral amor 22.jpg',
      'arreglo floral amor 23.jpg',
      'arreglo floral amor 24.jpg',
      'arreglo floral amor 25.jpg',
      'arreglo floral amor 26.jpg',
      'arreglo floral amor 27.jpg',
      'arreglo floral amor 28.jpg'
    ],
    'Cumpleaños': [
      'arreglo floral 1.jpg',
      'arreglo floral 2.jpg',
      'arreglo floral 3.jpg',
      'arreglo floral 4.jpg',
      'arreglo floral 5.jpg',
      'arreglo floral 6.jpg',
      'arreglo floral 7.jpg',
      'arreglo floral 8.jpg',
      'arreglo floral 9.jpg',
      'arreglo floral 10.jpg',
      'arreglo floral 11.jpg',
      'arreglo floral 12.jpg',
      'arreglo floral 13.jpg',
      'arreglo floral 14.jpg',
      'arreglo floral 15.jpg',
      'arreglo floral 16.jpg',
      'arreglo floral 17.jpg',
      'arreglo floral 18.jpg',
      'arreglo floral 19.jpg',
      'arreglo floral 20.jpg',
      'arreglo floral 21.jpg',
      'arreglo floral 22.jpg',
      'arreglo floral 23.jpg',
      'arreglo floral 24.jpg',
      'arreglo floral 25.jpg',
      'arreglo floral 26.jpg',
      'arreglo floral 27.jpg',
      'arreglo floral 28.jpg',
      'arreglo floral 29.jpg',
      'arreglo floral 30.jpg',
      'arreglo floral 31.jpg',
      'arreglo floral 32.jpg',
      'arreglo floral 33.jpg',
      'arreglo floral 34.jpg',
      'arreglo floral 35.jpg',
      'arreglo floral 36.jpg',
      'arreglo floral 37.jpg',
      'arreglo floral 38.jpg',
      'arreglo floral 39.jpg',
      'arreglo floral 40.jpg',
      'arreglo floral 41.jpg',
      'arreglo floral 42.jpg',
      'arreglo floral 43.jpg',
      'arreglo floral 44.jpg',
      'arreglo floral 45.jpg',
      'arreglo floral 46.jpg',
      'arreglo floral 47.jpg',
      'arreglo floral 48.jpg',
      'arreglo floral 49.jpg',
      'arreglo floral 50.jpg',
      'arreglo floral 51.jpg',
      'arreglo floral 52.jpg',
      'arreglo floral 53.jpg',
      'arreglo floral 54.jpg',
      'arreglo floral 55.jpg',
      'arreglo floral 56.jpg',
      'arreglo floral 57.jpg',
      'arreglo floral 58.jpg'
    ],
    'Funeral': [
      'arreglo funerario 1.jpg',
      'arreglo funerario 2.jpg',
      'arreglo funerario 3.jpg',
      'arreglo funerario 4.jpg',
      'arreglo funerario 5.jpg',
      'arreglo funerario 6.jpg',
      'arreglo funerario 7.jpg',
      'arreglo funerario 8.jpg',
      'arreglo funerario 9.jpg',
      'arreglo funerario 10.jpg',
      'arreglo funerario 11.jpg',
      'arreglo funerario 12.jpg',
      'arreglo funerario 13.jpg'
    ],
    'Navidad': [
      'centro de mesa navidad 1.jpg',
      'centro de mesa navidad 2.jpg',
      'centro de mesa navidad 3.jpg',
      'centro de mesa navidad 4.jpg',
      'centro de mesa navidad 5.jpg',
      'centro de mesa navidad 6.jpg',
      'centro de mesa navidad 7.jpg',
      'centro de mesa navidad 8.jpg'
    ]
  },
  'Bautizos': [
    'arreglo floral bautizo 1.jpg',
    'arreglo floral bautizo 2.jpg',
    'arreglo floral bautizo 3.jpg',
    'arreglo floral bautizo 4.jpg',
    'arreglo floral bautizo 5.jpg',
    'arreglo floral bautizo 6.jpg',
    'arreglo floral bautizo 7.jpg',
    'arreglo floral bautizo 8.jpg',
    'arreglo floral bautizo 9.jpg',
    'arreglo floral bautizo 10.jpg',
    'arreglo floral bautizo 11.jpg',
    'arreglo floral bautizo 12.jpg',
    'arreglo floral bautizo 13.jpg',
    'arreglo floral bautizo 14.jpg',
    'arreglo floral bautizo 15.jpg',
    'arreglo floral bautizo 16.jpg',
    'arreglo floral bautizo 17.jpg',
    'arreglo floral bautizo 18.jpg',
    'arreglo floral bautizo 19.jpg',
    'arreglo floral bautizo 20.jpg',
    'arreglo floral bautizo 21.jpg',
    'arreglo floral bautizo 22.jpg',
    'arreglo floral bautizo 23.jpg',
    'arreglo floral bautizo 24.jpg'
  ],
  'Bodas': {
    'Arreglo floral pasillos': [
      'arreglo floral para pasillo 1.jpg',
      'arreglo floral para pasillo 2.jpg',
      'arreglo floral para pasillo 3.jpg',
      'arreglo floral para pasillo 4.jpg',
      'arreglo floral para pasillo 5.jpg',
      'arreglo floral para pasillo 6.jpg',
      'arreglo floral para pasillo 7.jpg',
      'arreglo floral para pasillo 8.jpg',
      'arreglo floral para pasillo 9.jpg'
    ],
    'Arreglo para carro': [
      'arreglo floral para carro 1.jpg',
      'arreglo floral para carro 2.jpg',
      'arreglo floral para carro 3.jpg',
      'arreglo floral para carro 4.jpg',
      'arreglo floral para carro 5.jpg',
      'arreglo floral para carro 6.jpg',
      'arreglo floral para carro 7.jpg',
      'arreglo floral para carro 8.jpg',
      'arreglo floral para carro 9.jpg'
    ],
    'Boutonniere': [
      'boutonniere 1.jpg',
      'boutonniere 2.jpg',
      'boutonniere 3.png',
      'boutonniere 4.jpg',
      'boutonniere 5.jpg',
      'boutonniere 6.jpg',
      'boutonniere 7.jpg'
    ],
    'Centros de mesa': [
      'centro de mesa boda 1.jpg',
      'centro de mesa boda 2.jpg',
      'centro de mesa boda 3.jpg',
      'centro de mesa boda 5.jpg',
      'centro de mesa boda 6.jpg',
      'centro de mesa boda 7.jpg',
      'centro de mesa boda 8.jpg',
      'centro de mesa boda 9.jpg',
      'centro de mesa boda 10.jpg',
      'centro de mesa boda 11.jpg',
      'centro de mesa boda 12.jpg',
      'centro de mesa boda 13.jpg',
      'centro de mesa boda 14.jpg',
      'centro de mesa boda 15.jpg',
      'centro de mesa boda 16.jpg',
      'centro de mesa boda 17.jpg',
      'centro de mesa boda 18.jpg',
      'centro de mesa boda 19.jpg',
      'centro de mesa boda 20.jpg',
      'centro de mesa boda 21.jpg',
      'centro de mesa boda 22.jpg',
      'centro de mesa boda 23.jpg',
      'centro de mesa boda 24.jpg',
      'centro de mesa boda 25.jpg',
      'centro de mesa boda 26.jpg',
      'centro de mesa boda 27.jpg',
      'centro de mesa boda 28.jpg',
      'centro de mesa boda 29.jpg',
      'centro de mesa boda 30.jpg',
      'centro de mesa boda 31.jpg',
      'centro de mesa boda 32.jpg',
      'centro de mesa boda 33.jpg',
      'centro de mesa boda 34.jpg',
      'centro de mesa boda 35.jpg',
      'centro de mesa boda 36.jpg',
      'centro de mesa boda 37.jpg',
      'centro de mesa boda 38.jpg',
      'centro de mesa boda 39.jpg',
      'centro de mesa boda 40.jpg',
      'centro de mesa boda 41.jpg',
      'centro de mesa boda 42.jpg',
      'centro de mesa boda 43.jpg',
      'centro de mesa boda 44.jpg',
      'centro de mesa boda 45.jpg',
      'centro de mesa boda 46.jpg',
      'centro de mesa boda 47.jpg',
      'centro de mesa boda 48.jpg'
    ],
    'Decoración vintage': [
      'decoracion vintage 1.jpg',
      'decoracion vintage 2.jpg',
      'decoracion vintage 3.jpg',
      'decoracion vintage 4.jpg',
      'decoracion vintage 5.jpg'
    ],
    'Ramo tipo pomander': [
      'ramo tipo pomander 1.jpg',
      'ramo tipo pomander 2.jpg',
      'ramo tipo pomander 3.jpg',
      'ramo tipo pomander 4.png',
      'ramo tipo pomander 5.jpg',
      'ramo tipo pomander 6.jpg',
      'ramo tipo pomander 7.jpg',
      'ramo tipo pomander 8.png'
    ],
    'Ramos para aventar': [
      'ramo para aventar 1.jpg',
      'ramo para aventar 2.jpg',
      'ramo para aventar 3.jpg',
      'ramo para aventar 4.jpg',
      'ramo para aventar 5.jpg',
      'ramo para aventar 6.jpg',
      'ramo para aventar 7.jpg',
      'ramo para aventar 8.jpg'
    ],
    'Ramos para damas': [
      'ramos para damas 1.jpg',
      'ramos para damas 2.jpg',
      'ramos para damas 3.jpg',
      'ramos para damas 4.jpg',
      'ramos para damas 5.jpg',
      'ramos para damas 6.jpg',
      'ramos para damas 7.jpg',
      'ramos para damas 8.jpg'
    ],
    'Ramos tipo bouquets': [
      'ramo tipo bouquets 1.jpg',
      'ramo tipo bouquets 2.jpg',
      'ramo tipo bouquets 3.jpg',
      'ramo tipo bouquets 4.jpg',
      'ramo tipo bouquets 5.jpg',
      'ramo tipo bouquets 6.jpg',
      'ramo tipo bouquets 7.jpg',
      'ramo tipo bouquets 8.jpg',
      'ramo tipo bouquets 9.jpg',
      'ramo tipo bouquets 10.jpg',
      'ramo tipo bouquets 11.jpg',
      'ramo tipo bouquets 12.jpg',
      'ramo tipo bouquets 13.jpg',
      'ramo tipo bouquets 14.jpg',
      'ramo tipo bouquets 15.jpg',
      'ramo tipo bouquets 16.jpg',
      'ramo tipo bouquets 17.jpg',
      'ramo tipo bouquets 18.jpg',
      'ramo tipo bouquets 19.jpg',
      'ramo tipo bouquets 20.jpg',
      'ramo tipo bouquets 21.jpg'
    ],
    'Ramos tipo cascada': [
      'ramo tipo cascada 1.jpg',
      'ramo tipo cascada 2.jpg',
      'ramo tipo cascada 3.jpg',
      'ramo tipo cascada 4.jpg',
      'ramo tipo cascada 5.jpg',
      'ramo tipo cascada 6.jpg',
      'ramo tipo cascada 7.jpg',
      'ramo tipo cascada 8.jpg',
      'ramo tipo cascada 9.jpg',
      'ramo tipo cascada 10.jpg',
      'ramo tipo cascada 11.jpg',
      'ramo tipo cascada 12.jpg',
      'ramo tipo cascada 13.jpg'
    ]
  },
  'Eventos corporativos': [
    'arreglo floral 1.jpg',
    'arreglo floral 2.jpg',
    'arreglo floral 3.jpg',
    'arreglo floral 4.jpg',
    'arreglo floral 5.jpg',
    'arreglo floral 6.jpg',
    'arreglo floral 7.jpg',
    'arreglo floral 8.jpg',
    'arreglo floral 9.jpg',
    'arreglo floral 10.jpg',
    'arreglo floral 11.jpg',
    'arreglo floral 12.jpg',
    'arreglo floral 13.jpg',
    'arreglo floral 14.jpg',
    'arreglo floral 15.jpg',
    'arreglo floral 16.jpg',
    'arreglo floral 17.jpg',
    'arreglo floral 18.jpg',
    'arreglo floral 19.jpg',
    'arreglo floral 20.jpg',
    'arreglo floral 21.jpg',
    'arreglo floral 22.jpg',
    'arreglo floral 23.jpg',
    'arreglo floral 24.jpg',
    'arreglo floral 25.jpg',
    'arreglo floral 26.jpg',
    'arreglo floral 27.jpg',
    'arreglo floral 28.jpg',
    'arreglo floral 29.jpg',
    'arreglo floral 30.jpg',
    'arreglo floral 31.jpg',
    'arreglo floral 32.jpg',
    'arreglo floral 33.jpg',
    'arreglo floral 34.jpg',
    'arreglo floral 35.jpg',
    'arreglo floral 36.jpg',
    'arreglo floral 37.jpg',
    'arreglo floral 38.jpg',
    'arreglo floral 39.jpg',
    'arreglo floral 40.jpg',
    'arreglo floral 41.jpg',
    'arreglo floral 42.jpg',
    'arreglo floral 43.jpg',
    'arreglo floral 44.jpg',
    'arreglo floral 45.jpg',
    'arreglo floral 46.jpg',
    'arreglo floral 47.jpg',
    'arreglo floral 48.jpg',
    'arreglo floral 49.jpg',
    'arreglo floral 50.jpg',
    'arreglo floral 51.jpg',
    'arreglo floral 52.jpg',
    'arreglo floral 53.jpg',
    'arreglo floral 54.jpg',
    'arreglo floral 55.jpg',
    'arreglo floral 56.jpg',
    'arreglo floral 57.jpg',
    'arreglo floral 58.jpg',
    'arreglo floral 59.jpg',
    'arreglo floral 60.jpg',
    'arreglo floral 61.jpg',
    'arreglo floral 62.jpg',
    'arreglo floral 63.jpg',
    'arreglo floral 64.jpg',
    'arreglo floral 65.jpg',
    'arreglo floral 66.jpg',
    'arreglo floral 67.jpg',
    'arreglo floral 68.jpg',
    'arreglo floral 69.jpg',
    'arreglo floral 70.jpg',
    'arreglo floral 71.jpg',
    'arreglo floral 72.jpg',
    'arreglo floral 73.jpg',
    'arreglo floral 74.jpg',
    'arreglo floral 75.jpg',
    'arreglo floral 76.jpg',
    'arreglo floral 77.jpg'
  ],
  'Principal': [
    'principal 1.jpg',
    'principal 2.jpg',
    'principal 3.jpg',
    'principal 4.jpg',
    'principal 5.jpg',
    'principal 6.jpg',
    'principal 7.jpg',
    'principal 8.jpg',
    'principal 9.jpg',
    'principal 10.jpg',
    'principal 14 febrero.jpg'
  ],
  'XV Años': {
    'Arreglos para carro': [
      'Arreglo para Carro 1.jpg',
      'Arreglo para Carro 2.jpg',
      'Arreglo para Carro 3.jpg',
      'Arreglo para Carro 4.jpg',
      'Arreglo para Carro 5.jpg'
    ],
    'Centros de mesa': [
      'Centros de Mesa 1.jpg',
      'Centros de Mesa 2.jpg',
      'Centros de Mesa 3.jpg',
      'Centros de Mesa 4.jpg',
      'Centros de Mesa 5.jpg',
      'Centros de Mesa 6.jpg',
      'Centros de Mesa 7.jpg',
      'Centros de Mesa 8.jpg',
      'Centros de Mesa 9.jpg',
      'Centros de Mesa 10.jpg',
      'Centros de Mesa 11.jpg',
      'Centros de Mesa 12.jpg',
      'Centros de Mesa 13.jpg',
      'Centros de Mesa 14.jpg',
      'Centros de Mesa 15.jpg',
      'Centros de Mesa 16.jpg',
      'Centros de Mesa 17.jpg',
      'Centros de Mesa 18.jpg',
      'Centros de Mesa 19.jpg',
      'Centros de Mesa 20.jpg',
      'Centros de Mesa 21.jpg',
      'Centros de Mesa 22.jpg',
      'Centros de Mesa 23.jpg',
      'Centros de Mesa 24.jpg',
      'Centros de Mesa 25.jpg',
      'Centros de Mesa 26.jpg',
      'Centros de Mesa 27.jpg',
      'Centros de Mesa 28.jpg',
      'Centros de Mesa 29.jpg',
      'Centros de Mesa 30.jpg',
      'Centros de Mesa 31.jpg',
      'Centros de Mesa 32.jpg',
      'Centros de Mesa 33.jpg',
      'Centros de Mesa 34.jpg',
      'Centros de Mesa 35.jpg',
      'Centros de Mesa 36.jpg',
      'Centros de Mesa 37.jpg',
      'Centros de Mesa 38.jpg',
      'Centros de Mesa 39.jpg',
      'Centros de Mesa 40.jpg',
      'Centros de Mesa 41.jpg',
      'Centros de Mesa 42.jpg'
    ],
    'Ramos quinceañera': [
      'Ramo1.jpg',
      'Ramo2.jpg',
      'Ramo3.jpg',
      'Ramo4.jpg',
      'Ramo5.jpg',
      'Ramo6.jpg',
      'Ramo7.jpg',
      'Ramo8.jpg',
      'Ramo9.jpg',
      'Ramo10.jpg',
      'Ramo11.jpg'
    ]
  }
};

export const carouselItems = [
  {
    title: 'Sueño de invierno',
    description: 'Ramo de Pomander',
    image: 'img/flor1.jpg'
  },
  {
    title: 'Sueño de invierno',
    description: 'Ramo de Pomander',
    image: 'img/flor2.jpg'
  },
  {
    title: 'Sueño de invierno',
    description: 'Ramo de Pomander',
    image: 'img/flor3.jpg'
  },
  {
    title: 'Sueño de invierno',
    description: 'Ramo de Pomander',
    image: 'img/flor4.jpg'
  },
  {
    title: 'Sueño de invierno',
    description: 'Ramo de Pomander',
    image: 'img/flor5.jpg'
  },
  {
    title: 'Sueño de invierno',
    description: 'Ramo de Pomander',
    image: 'img/bouquet.jpg'
  },
  {
    title: 'Sueño de invierno',
    description: 'Ramo de Pomander',
    image: 'img/flor1.jpg'
  },
  {
    title: 'Sueño de invierno',
    description: 'Ramo de Pomander',
    image: 'img/flor2.jpg'
  },
  {
    title: 'Sueño de invierno',
    description: 'Ramo de Pomander',
    image: 'img/flor3.jpg'
  },
  {
    title: 'Sueño de invierno',
    description: 'Ramo de Pomander',
    image: 'img/flor4.jpg'
  },
  {
    title: 'Sueño de invierno',
    description: 'Ramo de Pomander',
    image: 'img/flor5.jpg'
  },
  {
    title: 'Sueño de invierno',
    description: 'Ramo de Pomander',
    image: 'img/bouquet.jpg'
  }
];
